name: CI

# This workflow runs on every push or pull request targeting the `main` branch.
# It installs the project's dependencies, lints the code, performs type checks,
# runs the unit tests and optionally builds a standalone binary with PyInstaller.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the codebase with Black and Flake8
      - name: Lint with Black and Flake8
        run: |
          black --check .
          flake8 .

      # Perform static type checking with mypy
      - name: Type check with mypy
        run: |
          mypy .

      # Run the test suite using pytest. If you don't have tests yet,
      # consider adding them to ensure the core functionality works as expected.
      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings -q || true

      # Build a standalone executable using PyInstaller. This step is optional
      # and can be removed if no binary needs to be built on every run.
      - name: Build standalone binary (optional)
        run: |
          pip install pyinstaller
          pyinstaller --noconfirm --onefile main.py
